Repository Flexicoder/dossier, pull requests merged in 2020-04, with the labels that each got.

#17 Creating bottom nav bar and stub pages
  codebase/Dossier/.babelrc
  codebase/Dossier/.eslintrc.js
  codebase/Dossier/App.tsx
  codebase/Dossier/index.js
  codebase/Dossier/package-lock.json
  codebase/Dossier/package.json
  codebase/Dossier/src/App.tsx
  codebase/Dossier/src/pages/Calendar.tsx
  codebase/Dossier/src/pages/Documents.tsx
  codebase/Dossier/src/pages/Home.tsx
  codebase/Dossier/src/pages/KeyInfo.tsx
  codebase/Dossier/src/pages/Symptoms.tsx
Labels: CORE

#20 Initial actions
  .github/workflows/ci.yml
Labels: infrastructure

#29 Updated Working Directoy in Github Action
  .github/workflows/ci.yml
Labels: bug, infrastructure

#30 Feature/issue 22
  .gitignore
  codebase/Dossier/.gitignore
  codebase/Dossier/__tests__/App-test.tsx
  codebase/Dossier/__tests__/components/HospitalNumber-test.tsx
  codebase/Dossier/__tests__/components/__snapshots__/HospitalNumber-test.tsx.snap
  codebase/Dossier/ios/Podfile.lock
  codebase/Dossier/package-lock.json
  codebase/Dossier/package.json
  codebase/Dossier/src/assets/styles.tsx
  codebase/Dossier/src/components/HospitalNumber.tsx
  codebase/Dossier/src/pages/KeyInfo.tsx
Labels: KEY INFORMATION
